"""
Generate a Markdown side-by-side comparison report across multiple platforms.

Usage:
    py gen_comparison_report.py [PLATFORM1 PLATFORM2 ...]
    # default: NVL-S NVL-H NVL-HX

Output:
    BOM_Comparison_Report_YYYYMMDD_HHMMSS.md  (in current directory)

Opens automatically in VS Code if `code` is on PATH.
"""
import json, subprocess, os, sys, datetime, glob
from collections import OrderedDict

PLATFORMS = sys.argv[1:] if len(sys.argv) > 1 else ["NVL-S", "NVL-H", "NVL-HX"]
HERE = os.path.dirname(os.path.abspath(__file__))
FILL_SCRIPT = os.path.normpath(os.path.join(HERE, "fill_b_column.py"))
JSON_PATH = os.path.join(os.environ.get("TEMP", "/tmp"), "bom_b_filled.json")
OUT_DIR = os.getcwd()
TS = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
REPORT = os.path.join(OUT_DIR, f"BOM_Comparison_Report_{TS}.md")

data = OrderedDict()
for pf in PLATFORMS:
    subprocess.run(["py", FILL_SCRIPT, pf], capture_output=True, text=True)
    d = json.load(open(JSON_PATH, encoding="utf-8"))
    data[pf] = {r["A"]: r["B"] for r in d["rows"]}

subsystems = list(next(iter(data.values())).keys())

lines = [
    f"# BOM Risk Assessment - Platform Comparison Report",
    "",
    f"**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  ",
    f"**Platforms compared:** {', '.join(PLATFORMS)}  ",
    "",
    "## Differences Across Platforms",
    "",
]

diffs = []
for s in subsystems:
    vals = [data[pf].get(s, "") for pf in PLATFORMS]
    if len(set(vals)) > 1:
        diffs.append((s, vals))

if not diffs:
    lines.append("_All subsystems have identical Column B content across the compared platforms._")
else:
    lines.append(f"**{len(diffs)} subsystem(s) differ** between platforms:")
    lines.append("")
    for s, vals in diffs:
        lines.append(f"### {s}")
        lines.append("")
        header = "| Platform | " + " Column B |"
        sep = "|----------|" + "----------|"
        lines.append("| Platform | Column B |")
        lines.append("|----------|----------|")
        for pf, v in zip(PLATFORMS, vals):
            v_disp = v.replace("\n", "<br>") if v else "_(empty)_"
            lines.append(f"| **{pf}** | {v_disp} |")
        lines.append("")

lines.append("## Full Side-by-Side Mapping")
lines.append("")
header_cols = " | ".join(PLATFORMS)
sep_cols = " | ".join(["-------"] * len(PLATFORMS))
lines.append(f"| Subsystem | {header_cols} |")
lines.append(f"|-----------|-{sep_cols}-|")
for s in subsystems:
    cells = []
    for pf in PLATFORMS:
        v = data[pf].get(s, "")
        v_disp = v.replace("\n", "<br>") if v else "_(empty)_"
        if len(v_disp) > 300:
            v_disp = v_disp[:300] + "..."
        cells.append(v_disp)
    lines.append(f"| **{s}** | " + " | ".join(cells) + " |")
lines.append("")

lines.append("## Generated Excel Files")
lines.append("")
xlsx = sorted(glob.glob(os.path.join(OUT_DIR, "*BOM_Risk_Assessment_*.xlsx")),
              key=os.path.getmtime, reverse=True)[:len(PLATFORMS)]
for f in xlsx:
    name = os.path.basename(f)
    lines.append(f"- [`{name}`](./{name})")
lines.append("")
lines.append("---")
lines.append("")
lines.append("_Report generated by the bom-risk skill._")

with open(REPORT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Report: {REPORT}")

# Auto-open in VS Code if available
try:
    subprocess.Popen(["code", REPORT], shell=True)
except Exception:
    pass
